FROM node:14-alpine
WORKDIR /usr/app

#プロジェクト作成済み
#package.json整理済み
RUN npm i

#手動でプロジェクト作成
#RUN npx create-react-app . --template redux-typescript --use-npm

#必要ライブラリ
#RUN npm i create-react-app
#RUN npm i react-router-dom@5.3.0 @types/react-router-dom@5.3.1
#RUN npm i react-scripts
#RUN npm i typescript
#RUN npm i axios
#RUN npm i @mui/material @emotion/react @emotion/styled
#RUN npm i @mui/styled-engine-sc styled-components
#RUN npm i @mui/styles
#RUN npm i @mui/icons-material